Update to Extreme Tux Racer 0.8.2
flathub/net.sourceforge.ExtremeTuxRacer pull request #9
Opened 2022-07-04 18:22 UTC by Newbytee

I tried using upstream's metainfo, but it has issues (doesn't validate and is installed as etr.appdata.xml rather than etr.metainfo.xml) so I'm keeping the downstream one for now.

2022-07-04 19:33 UTC, hfiguiere commented
> I tried using upstream's metainfo, but it has issues (doesn't validate

Patch then

> and is installed as etr.appdata.xml rather than etr.metainfo.xml) so I'm keeping the downstream one for now.

this actually doesn't matter.

2022-07-08 04:08 UTC, Newbytee commented
bot, build

2022-07-08 13:28 UTC, hfiguiere requested changes

2022-07-08 13:28 UTC, hfiguiere commented on net.sourceforge.ExtremeTuxRacer.json
> -                "install -Dm644 etr.metainfo.xml /app/share/metainfo",
you probably need to add a `rename-appdata-file` in the top leverl to rename the upstream metainfo.

2022-07-08 13:28 UTC, hfiguiere commented on etr.metainfo.xml
>      </screenshot>
and since you patch upstream now, you should remove this file from the repo.

2022-07-08 18:26 UTC, Newbytee commented
bot, build

2022-07-11 00:09 UTC, hfiguiere approved these changes

2022-07-25 02:43 UTC, merged